[package]
name = "catpack"
version = "0.1.0"
edition = "2024"

[dependencies]
lz4_flex = { version = "0.11.5", optional = true }

[features]
# Enables lz4 (lossless) compression & decompression of package data using the crate `lz4_flex`
lz4 = ["dep:lz4_flex"]